eventrecommender/config/routes.rb
Eventrecommender::Application.routes.draw do
  resources :interests

  resources :events

  resources :users

  root :to => "events#index"

end

eventrecommender/app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :location, :name, :url

  has_many :attendees
  has_many :event_interests
end

eventrecommender/app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

eventrecommender/app/helpers/events_helper.rb
module EventsHelper
end

eventrecommender/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eventrecommender/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

eventrecommender/app/views/events/index.html.erb
<div data-role="page">
  <div data-role="header">
    <a href="#" data-icon="home">Home</a>
    <h4>Find Events</h4>
    <a href="index.html" data-icon="gear" class="ui-btn-right">Filter</a>
  </div>
  <div data-role="content">
    <input type="search" name="search-mini" id="search-mini" value="" data-mini="true" />
    <ul id="event-list" data-role="listview">
      <% @events.each do |event| %>
        <li>
          <%= link_to event, :class => "ui-link-inherit" do %>
            <img src="http://placehold.it/80" class="ui-li-thumb">
            <h3 class="ui-li-heading"><%= event.name %></h3>
            <p class="ui-li-desc"><%= event.location %></p>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <br />
  <div data-role="footer">
    <div data-role="navbar">
      <ul>
        <li><%= link_to 'Find Events', events_path %></li>
        <li><%= link_to 'My Events', events_path %></li>
        <li><%= link_to 'Settings', interests_path %></li>
      </ul>
    </div><!-- /navbar -->
  </div>
</div>

<%= link_to 'New Event', new_event_path %>

eventrecommender/app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

eventrecommender/app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Date:</b>
  <%= @event.date %>
</p>

<p>
  <b>Location:</b>
  <%= @event.location %>
</p>

<p>
  <b>Url:</b>
  <%= @event.url %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>