eventrecommender/config/routes.rb
Eventrecommender::Application.routes.draw do
  resources :interests

  resources :events

  resources :users

  root :to => "events#index"

end

eventrecommender/app/models/event_interest.rb
class EventInterest < ActiveRecord::Base
  attr_accessible :event_id, :interest_id

  belongs_to :interest
  belongs_to :event
end

eventrecommender/app/controllers/event_interests_controller.rb
class EventInterestsController < ApplicationController
  # GET /event_interests
  # GET /event_interests.json
  def index
    @event_interests = EventInterest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @event_interests }
    end
  end

  # GET /event_interests/1
  # GET /event_interests/1.json
  def show
    @event_interest = EventInterest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event_interest }
    end
  end

  # GET /event_interests/new
  # GET /event_interests/new.json
  def new
    @event_interest = EventInterest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event_interest }
    end
  end

  # GET /event_interests/1/edit
  def edit
    @event_interest = EventInterest.find(params[:id])
  end

  # POST /event_interests
  # POST /event_interests.json
  def create
    @event_interest = EventInterest.new(params[:event_interest])

    respond_to do |format|
      if @event_interest.save
        format.html { redirect_to @event_interest, notice: 'Event interest was successfully created.' }
        format.json { render json: @event_interest, status: :created, location: @event_interest }
      else
        format.html { render action: "new" }
        format.json { render json: @event_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /event_interests/1
  # PUT /event_interests/1.json
  def update
    @event_interest = EventInterest.find(params[:id])

    respond_to do |format|
      if @event_interest.update_attributes(params[:event_interest])
        format.html { redirect_to @event_interest, notice: 'Event interest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event_interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_interests/1
  # DELETE /event_interests/1.json
  def destroy
    @event_interest = EventInterest.find(params[:id])
    @event_interest.destroy

    respond_to do |format|
      format.html { redirect_to event_interests_url }
      format.json { head :no_content }
    end
  end
end

eventrecommender/app/helpers/event_interests_helper.rb
module EventInterestsHelper
end

eventrecommender/app/views/event_interests/_form.html.erb
<%= form_for(@event_interest) do |f| %>
  <% if @event_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_interest.errors.count, "error") %> prohibited this event_interest from being saved:</h2>

      <ul>
      <% @event_interest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :interest_id %><br />
    <%= f.number_field :interest_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

eventrecommender/app/views/event_interests/edit.html.erb
<h1>Editing event_interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_interest %> |
<%= link_to 'Back', event_interests_path %>

eventrecommender/app/views/event_interests/index.html.erb
<h1>Listing event_interests</h1>

<table>
  <tr>
    <th>Event</th>
    <th>Interest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @event_interests.each do |event_interest| %>
  <tr>
    <td><%= event_interest.event_id %></td>
    <td><%= event_interest.interest_id %></td>
    <td><%= link_to 'Show', event_interest %></td>
    <td><%= link_to 'Edit', edit_event_interest_path(event_interest) %></td>
    <td><%= link_to 'Destroy', event_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Event interest', new_event_interest_path %>

eventrecommender/app/views/event_interests/new.html.erb
<h1>New event_interest</h1>

<%= render 'form' %>

<%= link_to 'Back', event_interests_path %>

eventrecommender/app/views/event_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event:</b>
  <%= @event_interest.event_id %>
</p>

<p>
  <b>Interest:</b>
  <%= @event_interest.interest_id %>
</p>


<%= link_to 'Edit', edit_event_interest_path(@event_interest) %> |
<%= link_to 'Back', event_interests_path %>